config/routes.rb
Pickaxe::Application.routes.draw do
  root to: "programs#index"
  

  resources :programs
  get 'robot/halt' => 'programs#halt', as: :robot_halt
  resources :programs do
    post 'compile', on: :member
  end
  
end

app/models/program.rb
class Program < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :instructions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  inherit_resources
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController

  def halt
  end
  
  def compile
    @program = Program.find params[:id]

    @instructions = @program.instructions
    if params.has_key? :configuration and not params[:configuration].blank?
      params[:configuration].each do |variable|
        unless variable.blank?
          variable_name = variable[0]
          variable_value = variable[1]
          @instructions.gsub! "{#{variable_name}}", variable_value
        end
      end
    end

    file = Tempfile.new @program.name.parameterize
    file.write @instructions.gsub("\n", "").gsub("\r", "")
    file.close

    usb_port = "/dev/tty.usbserial-00001014"
    @command = "./picaxe20x2 -c#{usb_port} #{file.path}"
    @result = `#{@command}`  
    flash.now[:alert] = "Successfully compiled and installed program!"
  end

  def permitted_params
    params.permit program: [:name, :instructions], configuration: []
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/application/_flash.haml
- flash.each do |name, message|
  - if message.is_a?(String)
    = content_tag :p, message, class: "flash #{name}"

app/views/application/_head.haml
!!!
%html
  %head
    %title Pickaxe
    %meta{content: 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no', name: 'viewport'}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "http://d3js.org/d3.v3.min.js", "data-turbolinks-track" => true
    = javascript_include_tag "http://js.leapmotion.com/0.3.0/leap.js", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

app/views/layouts/application.html.haml
= render 'head'
%body
  #header
    %div
      %a{ href: root_path }
        %h1 Pickaxe
      = render 'flash'
  = yield
  #footer
    %div
      %cite Designed in beautiuful Boulder, Colorado.

app/views/programs/_form.haml
= simple_form_for @program do |f|
  = f.input :name
  = f.input :instructions
  .input
    = f.submit class: :button

app/views/programs/compile.html.haml
#program
  %div
    %h2= @program.name
    %h3 Program
    %pre= @instructions
    %h3 Command
    %pre= @command
    %h3 Result
    %pre= @result

    = link_to "Back", @program, class: :button

app/views/programs/edit.html.haml
#program-edit
  %div
    %h2 Edit Program
    = render 'form'

app/views/programs/index.html.haml
.container
  .content
    %table
      %tr
        %th{ colspan: 2} Program
      - if @programs.count > 0
        - @programs.each do |program|
          %tr
            %td= link_to program.name, program_path(program)
            %td.actions
              = link_to "Edit", edit_program_path(program)
              = link_to "Delete", program, method: :delete, data: { confirm: 'Are you sure?' }
      - else
        %tr
          %td There are no programs written yet
    = link_to "New Program", new_program_path, class: :button

app/views/programs/new.html.haml
#program-new
  %div
    %h2 New Program
    = render 'form'

app/views/programs/show.html.haml
#program
  %div
    %h2= @program.name
    %pre= @program.instructions
    = link_to "Edit Program", edit_program_path(@program), class: :button
    %h3 Compile Program
    = form_tag compile_program_path(@program) do
      - variables = []
      - @program.instructions.scan(/{(.*?)}/).each do |string|
        - unless variables.include? string
          - variables << string
          .input
            %label= string[0].titleize
            = text_field_tag "configuration[#{string[0]}]"
      = submit_tag "Compile and Install", class: :button